[package]
name = "dioxus-toastr"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.7.2", features = ["web"] }
futures-timer = "3"
gloo-timers = { version = "0.3", features = ["futures"] }
